from logging import Logger
import sys
import ast
from functools import reduce
from itertools import chain, combinations
import time 
from .utils import get_key, get_set
from typing import List, Set, Dict, FrozenSet

class Topology:
    
    """ This class defines an object Topology """
    
   
    def __init__(self, E, S = None):
        """
        This is the constructor for Topology.

        Args:
            E (list/dictionary): List of pieces of evidence / Dictionary with pieces of evidence as keys and certainty degree as values.
            S (set, optional): Total set. 

        Returns:
            None
        """

        if E is None:
            raise ValueError("E (Evidence) argument must be provided.")

        if isinstance(E, dict):
            E = [get_set(k) for k in E.keys()]

        if S is None:
            S = set().union(*E)

        self.S = S
        self.E = E
    
    
    def get_subbasis(self):
        """
        This methods returns the subbasis of the topology generated by a collection of pieces of evidence. This is exactly the list of pieces of evidence. 

        Returns:
            E (list):   Evidence
        """
        
        return self.E
    
    def get_basis(self) -> list[set]:
        """
        This method computes the basis of the topology generated by the evidence. Namely, the closure by finite intersections of the subbais.
        
        Returns:
            basis (list) : The basis of the topology.
        """
        B = set()
        for S in self.get_subbasis():
            new_B = {frozenset(S)}
            for b in B:
                intersection = b & frozenset(S)
                if intersection:  # ignore empty intersections
                    new_B.add(intersection)
            B |= new_B
        return [set(x) for x in B]

    def get_topology(self):
        """
        This methods returns the topology generated by the evidence. Namely, the closure by finite intersections and unions of the basis, plus the empty set and the total set.

        Returns:
            topology (list) : The topology.
        """

        basis = self.get_basis()
        topology = basis  # Initialize the topology with the basis elements

        # Add the empty set
        if set() not in topology:
            topology.append(set())

        # Add the total set
        if self.S not in topology:
            topology.append(self.S) 
        
        updated = True

        while updated:
            updated = False

            for size in range(2, len(basis) + 1):
                combinations_size = combinations(basis, size) # Generate all combinations of size 'size' from the basis elements

                for combination in combinations_size:
                    union = set().union(*combination)  # Compute the union of the combination elements
                    if union not in topology:
                        topology.append(union)  # Add the union to the topology
                        updated = True

        return topology

    def get_dense_sets(self):
        """
        This method computes the set of dense elements of the topology. 
        A set T is dense in the topology if (i) it belongs to the topology 
        and (ii) has a non-empty intersection with every non-empty set in the topology.

        Returns:
            dense_sets (list) : The set of dense sets of the topology.
        """
        topology = self.get_topology()
        topology.remove(set())
        dense_sets = []

        for candidate_set in topology:
            is_dense = True

            for other_set in topology:
                if not candidate_set.intersection(other_set): # Check all possible intersections
                    is_dense = False
                    break

            if is_dense:
                dense_sets.append(candidate_set)

        return dense_sets        


    def print(self):
        """
        This methods prints all the methods of the Topology class.

        Returns:
            None
        """

        print("Subbasis: " + str(self.get_subbasis()))
        print("Basis: " + str(self.get_basis()))
        print("Topology: ", str(self.get_topology()))
        print("Dense sets: ", str(self.get_dense_sets()))
        
    
    def minimal_dense_set(sets, logger: Logger):
        """
        This function computes the smallest dense set of a topology generated from a list of sets.
        A set S is dense if (i) it belongs to the topology and (ii) has a non-empty intersection with every set in the topology.

        Args:
            sets (list): A list of pieces of evidence.

        Returns:
            (set): The smallest dense set of the topology.
        """
        
        # logger.info(f"Starting to find the minimal dense set from imput {sets}...")
        print(f"Starting to find the minimal dense set from imput {sets}...")
        
        st = time.perf_counter()
        topology = Topology(sets)
        dense_sets = topology.get_dense_sets() # qui auch
        out = min(dense_sets, key=len, default=topology.S)
        en = time.perf_counter()
        
        # logger.info(f"...a time of {en-st} seconds was required to find the minimal dense set.")
        print(f"...a time of {en-st} seconds was required to find the minimal dense set.")

        return out

def minimal_dense_set_gpt(sets, logger: Logger):
    """
    Find an inclusion-minimal open dense set in the finite topology
    generated by `sets` (pieces of evidence).

    In a finite topology, this is the same as a minimum-cardinality
    open dense set.
    """

    logger.info(f"Starting to find an inclusion-minimal open dense set from input {sets}...")
    start = time.perf_counter()

    topo = Topology(sets)
    S = list(topo.S)
    n = len(S)

    # Non-empty basis elements
    basis = [set(b) for b in topo.get_basis() if b]

    # Edge cases
    if n == 0:
        # Empty space: by convention return empty set
        logger.info("Ground set is empty; returning empty set.")
        return set()

    if not basis:
        # Only opens are ∅ and S, and S is dense.
        logger.info("Basis is empty; S is the only nonempty open dense set.")
        return set(S)

    # Enumerate subsets of S in increasing size
    for k in range(1, n + 1):
        logger.info(f"Subset of length {k} out of {n}...")
        for idxs in combinations(range(n), k):
            D = {S[i] for i in idxs}

            # --- Check openness: D is union of basis elements ---
            open_ok = True
            for x in D:
                # Need at least one basis element b with x in b and b ⊆ D
                if not any((x in b and b.issubset(D)) for b in basis):
                    open_ok = False
                    break
            if not open_ok:
                continue

            # --- Check density: D intersects every basis element ---
            dense_ok = all(D & b for b in basis)
            if not dense_ok:
                continue

            # Found minimal-cardinality (hence inclusion-minimal) open dense set
            end = time.perf_counter()
            logger.info(
                f"...found inclusion-minimal open dense set of size {k} "
                f"in {end - start:.6f} seconds: {D}"
            )
            return D

    # Fallback: S is always open and dense
    end = time.perf_counter()
    logger.warning(
        f"No smaller open dense set found; returning S (size {n}) "
        f"after {end - start:.6f} seconds."
    )
    return set(S)

def minimum_open_dense_set_gpt_thesis(evidence_sets: List[Set[str]], logger: Logger) -> Set[str]:
    """
    Given a qualitative evidence family E as a list of sets of states (strings),
    compute the minimum open dense set M of the topology generated by E as a
    sub-basis, following the algorithm described via the identical support
    relation ~_E.

    Parameters
    ----------
    evidence_sets : list[set[str]]
        The qualitative evidence set E ⊆ 2^S.
        Each element is a set of states (strings).

    Returns
    -------
    set[str]
        The minimum open dense set M ⊆ S.

    Notes
    -----
    - The state space S is taken to be the union of all sets in `evidence_sets`.
    - Two states a, b ∈ S are equivalent (a ~_E b) iff for every E ∈ evidence_sets,
      a ∈ E iff b ∈ E (identical support relation).
    - We:
        1) Compute the equivalence classes S / ~_E.
        2) For each equivalence class [a], compute the intersection of all E' ∈ E'
           that contain {[a]}. This intersection equals the set of classes whose
           support pattern includes the support of [a].
        3) Keep [a] if that intersection is exactly {[a]}.
        4) Let M' be the union of the kept classes in S / ~_E.
        5) Let M be the union of the corresponding states in S.
    """

    logger.info(f"Starting to find an inclusion-minimal open dense set from input {evidence_sets}...")
    start = time.perf_counter()

    # Step 0: Build the underlying state space S
    S: Set[str] = set()
    for ev in evidence_sets:
        S.update(ev)

    # Edge case: no states
    if not S:
        return set()

    # Step 1: For each state, compute its "support pattern":
    # support[s] = frozenset of indices i such that s ∈ evidence_sets[i]
    support: Dict[str, FrozenSet[int]] = {}
    for s in S:
        idxs = {i for i, ev in enumerate(evidence_sets) if s in ev}
        support[s] = frozenset(idxs)

    # Step 2: Build equivalence classes S / ~_E:
    # states with the same support pattern go in the same class.
    pattern_to_class: Dict[FrozenSet[int], Set[str]] = {}
    for s, pat in support.items():
        pattern_to_class.setdefault(pat, set()).add(s)

    # Now we have:
    # - patterns: the support patterns (each is a frozenset of evidence indices)
    # - classes: the equivalence classes (each is a set of states)
    patterns = list(pattern_to_class.keys())

    # Step 3: For each equivalence class [a] with pattern P,
    # compute intersection of all E' that contain {[a]} and check if it is {[a]}.
    #
    # As argued in the text:
    # - E'_i = { classes whose pattern contains index i }.
    # - For class with pattern P, the E' that contain it are those with i ∈ P.
    # - Their intersection is exactly the set of classes whose pattern Q satisfies P ⊆ Q.
    #
    # Thus {[a]} is kept iff there is no other class with pattern Q ⊃ P.
    # In other words, P is *maximal* under subset inclusion among all patterns.

    # Find which patterns are inclusion-maximal
    maximal_patterns: Set[FrozenSet[int]] = set()
    for P in patterns:
        # P is maximal if there is no Q with P ⊂ Q
        if not any(P < Q for Q in patterns):
            maximal_patterns.add(P)

    # Step 4: M' is the union of the classes whose pattern is maximal
    # Step 5: M (subset of S) is the union of states in those classes
    M: Set[str] = set()
    for pat in maximal_patterns:
        M.update(pattern_to_class[pat])

    end = time.perf_counter()
    logger.info(f"Minimal dense set found after {end - start:.6f} seconds.")

    return M


class DummyLogger:
    def info(self, *args, **kwargs):
        print("INFO> ", args, kwargs)


def is_open_dense(topo: Topology, D: set) -> bool:
    """
    Check that D is open and dense in the topology 'topo',
    *using only the basis*, as per your definitions.
    """
    S = set(topo.S)
    if not D.issubset(S):
        return False

    basis = [set(b) for b in topo.get_basis() if b]

    # Open: D is a union of basis elements
    for x in D:
        if not any((x in b and b.issubset(D)) for b in basis):
            return False

    # Dense: D intersects every non-empty basis element
    for b in basis:
        if not (D & b):
            return False

    return True


# --- Test cases ---

def test_single_evidence(function):
    """
    E = [{1,2,3}]
    Basis = [{1,2,3}]
    Only non-empty open dense set is {1,2,3}.
    """
    logger = DummyLogger()
    sets = [ {1, 2, 3} ]
    topo = Topology(sets)

    D = function(sets, logger)

    assert D == {1, 2, 3}
    assert is_open_dense(topo, D)


def test_overlapping_evidence_singleton_dense(function):
    """
    E = [{1,2}, {2,3}]
    Basis = [{1,2}, {2,3}, {2}]
    Open dense sets include {2}, {1,2}, {2,3}, {1,2,3}.
    Smallest is {2}.
    """
    logger = DummyLogger()
    sets = [ {1, 2}, {2, 3} ]
    topo = Topology(sets)

    D = function(sets, logger)

    assert D == {2}
    assert is_open_dense(topo, D)


def test_minimal_dense_needs_two_points(function):
    """
    E = [{1}, {2}, {1,2,3}]
    Basis (non-empty) = [{1}, {2}, {1,2,3}]
    Open dense sets: {1,2}, {1,2,3}
    Smallest is {1,2}.
    """
    logger = DummyLogger()
    sets = [ {1}, {2}, {1, 2, 3} ]
    topo = Topology(sets)

    D = function(sets, logger)

    assert D == {1, 2}
    assert is_open_dense(topo, D)


def test_only_full_space_is_dense(function):
    """
    E = [{1,2}, {3}]
    Basis = [{1,2}, {3}]
    Open sets = ∅, {1,2}, {3}, {1,2,3}.
    Only open dense set is {1,2,3}.
    """
    logger = DummyLogger()
    sets = [ {1, 2}, {3} ]
    topo = Topology(sets)

    D = function(sets, logger)

    assert D == {1, 2, 3}
    assert is_open_dense(topo, D)


def test_empty_space(function):
    """
    Edge case: empty ground set.
    If E = [∅], S = ∅, basis = [].
    Function should return ∅.
    """
    logger = DummyLogger()
    sets = [ set() ]
    topo = Topology(sets)

    D = function(sets, logger)

    assert D == set()
    # In the empty space, treat empty as vacuously open/dense
    assert D == set(topo.S)
    
def test_battery_ex(function):
    logger = DummyLogger()
    sets = [{'3CubesSystem', 'PowerIndicator', 'ParallelLoad', 'LoadModule', 'MainLoad'},
    {'Switch', '3CubesSystem', 'MainLoad', 'PowerIndicator', 'ParallelLoad', 'LoadModule', 'ControlModule', 'PowerSupplyModule'},
    {'Switch', 'Battery', 'Cables'},
    {'Switch', 'Cables', 'Battery', 'MainLoad'},
    {'PowerIndicator', 'Battery'},]

    D = function(sets, logger)

    assert D == {'Switch', 'MainLoad', 'PowerIndicator', 'Battery'}
    


def test_random_small_example_property_check(function):
    """
    A small random-ish example where we don't know the closed form,
    but we can still verify the result is open and dense and that
    no smaller open dense subset exists.
    """
    logger = DummyLogger()
    sets = [
        {1, 2},
        {2, 3},
        {3, 4},
    ]
    topo = Topology(sets)
    S = set(topo.S)

    D = function(sets, logger)
    assert is_open_dense(topo, D)

    # Check no proper subset of D is open dense (inclusion-minimality)
    from itertools import combinations
    D_list = list(D)
    for k in range(1, len(D)):
        for idxs in combinations(range(len(D_list)), k):
            D_sub = {D_list[i] for i in idxs}
            assert not is_open_dense(topo, D_sub)


if __name__ == "__main__":
    function = minimal_dense_set_gpt
    function = minimum_open_dense_set_gpt_thesis
    # Run tests manually
    # test_single_evidence(function)
    # test_overlapping_evidence_singleton_dense(function)
    # test_minimal_dense_needs_two_points(function)
    # test_only_full_space_is_dense(function)
    # test_empty_space(function)
    # test_random_small_example_property_check(function)
    test_battery_ex(function)
    print("All tests passed.")
